<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.1.0-alpha.5</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LoLCompanion.Core\LoLCompanion.Core.csproj" />
  </ItemGroup>
</Project>
